@startuml DispositionOverview

(*) -->[Data Chunk(s)] "Data Transformation"
-->[Data Chunk(s)] "Output Generation"
-->[Output Chunk(s)] "Output Transformation"
-->[Output Chunk(s)] "Output Dispostion"
"Output Dispostion" -down->[Result Chunk(s)] (*)
"Output Dispostion" -right-> "Child Output Dispostion 1"
--> "Output Dispostion"
"Output Dispostion" -right-> "Child Output Dispostion 2"
--> "Output Dispostion"
"Output Dispostion" -right-> "Child Output Dispostion 3"
--> "Output Dispostion"


@enduml
